# Generated by Django 5.1.2 on 2024-10-13 02:32

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(default=''),
        ),
    ]
